-- MySQL Script generated by MySQL Workbench
-- Tue Nov 12 16:04:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema qairline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qairline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qairline` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `qairline` ;

-- -----------------------------------------------------
-- Table `qairline`.`airplane`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`airplane` ;

CREATE TABLE IF NOT EXISTS `qairline`.`airplane` (
  `idAirplane` INT NOT NULL,
  PRIMARY KEY (`idAirplane`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qairline`.`airport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`airport` ;

CREATE TABLE IF NOT EXISTS `qairline`.`airport` (
  `idairport` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idairport`),
  UNIQUE INDEX `idairport_UNIQUE` (`idairport` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qairline`.`classflight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`classflight` ;

CREATE TABLE IF NOT EXISTS `qairline`.`classflight` (
  `idclassFlight` INT NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `seatAmount` INT UNSIGNED NULL DEFAULT NULL,
  `seatBooked` INT(10) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `currentPrice` INT(10) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  PRIMARY KEY (`idclassFlight`),
  UNIQUE INDEX `idclassFlight_UNIQUE` (`idclassFlight` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qairline`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`customer` ;

CREATE TABLE IF NOT EXISTS `qairline`.`customer` (
  `idCustomer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCustomer`),
  UNIQUE INDEX `id_UNIQUE` (`idCustomer` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qairline`.`flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`flight` ;

CREATE TABLE IF NOT EXISTS `qairline`.`flight` (
  `idFlight` INT NOT NULL,
  `timeStart` TIME NULL DEFAULT NULL,
  `timeEnd` TIME NULL DEFAULT NULL,
  `idbeginAirport` INT UNSIGNED NOT NULL,
  `idendAirport` INT UNSIGNED NOT NULL,
  `idclassFlight` INT NOT NULL,
  `idAirplane` INT NOT NULL,
  PRIMARY KEY (`idFlight`),
  UNIQUE INDEX `idflight_UNIQUE` (`idFlight` ASC) VISIBLE,
  INDEX `fk_flight_airport1_idx` (`idbeginAirport` ASC) VISIBLE,
  INDEX `fk_flight_airport2_idx` (`idendAirport` ASC) VISIBLE,
  INDEX `fk_flight_classFlight1_idx` (`idclassFlight` ASC) VISIBLE,
  INDEX `fk_flight_airplane1_idx` (`idAirplane` ASC) VISIBLE,
  CONSTRAINT `fk_flight_airplane1`
    FOREIGN KEY (`idAirplane`)
    REFERENCES `qairline`.`airplane` (`idAirplane`),
  CONSTRAINT `fk_flight_airport1`
    FOREIGN KEY (`idbeginAirport`)
    REFERENCES `qairline`.`airport` (`idairport`),
  CONSTRAINT `fk_flight_airport2`
    FOREIGN KEY (`idendAirport`)
    REFERENCES `qairline`.`airport` (`idairport`),
  CONSTRAINT `fk_flight_classFlight1`
    FOREIGN KEY (`idclassFlight`)
    REFERENCES `qairline`.`classflight` (`idclassFlight`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qairline`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`ticket` ;

CREATE TABLE IF NOT EXISTS `qairline`.`ticket` (
  `idTicket` INT NOT NULL,
  `idclassFlight` INT NOT NULL,
  `idCustomer` INT UNSIGNED NOT NULL,
  `price` INT ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`idTicket`),
  UNIQUE INDEX `idticket_UNIQUE` (`idTicket` ASC) VISIBLE,
  INDEX `fk_ticket_classFlight1_idx` (`idclassFlight` ASC) VISIBLE,
  INDEX `fk_ticket_customer1_idx` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_classFlight1`
    FOREIGN KEY (`idclassFlight`)
    REFERENCES `qairline`.`classflight` (`idclassFlight`),
  CONSTRAINT `fk_ticket_customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `qairline`.`customer` (`idCustomer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
