-- MySQL Script generated by MySQL Workbench
-- Sat Nov 16 00:53:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema qairline
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `qairline` ;

-- -----------------------------------------------------
-- Schema qairline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qairline` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `qairline` ;

-- -----------------------------------------------------
-- Table `qairline`.`airplane`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`airplane` ;

CREATE TABLE IF NOT EXISTS `qairline`.`airplane` (
  `idAirplane` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idAirplane`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qairline`.`airport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`airport` ;

CREATE TABLE IF NOT EXISTS `qairline`.`airport` (
  `idairport` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`idairport`),
  UNIQUE INDEX `idairport_UNIQUE` (`idairport` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qairline`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`admin` ;

CREATE TABLE IF NOT EXISTS `qairline`.`admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idAdmin_UNIQUE` (`idAdmin` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qairline`.`flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`flight` ;

CREATE TABLE IF NOT EXISTS `qairline`.`flight` (
  `idFlight` INT NOT NULL AUTO_INCREMENT,
  `timeStart` DATETIME NULL DEFAULT NULL,
  `timeEnd` DATETIME NULL DEFAULT NULL,
  `idbeginAirport` INT UNSIGNED NOT NULL,
  `idendAirport` INT UNSIGNED NOT NULL,
  `idAirplane` INT NOT NULL,
  `idAdmin_created` INT NOT NULL,
  PRIMARY KEY (`idFlight`),
  UNIQUE INDEX `idflight_UNIQUE` (`idFlight` ASC) VISIBLE,
  INDEX `fk_flight_airport1_idx` (`idbeginAirport` ASC) VISIBLE,
  INDEX `fk_flight_airport2_idx` (`idendAirport` ASC) VISIBLE,
  INDEX `fk_flight_airplane1_idx` (`idAirplane` ASC) VISIBLE,
  INDEX `fk_flight_admin1_idx` (`idAdmin_created` ASC) VISIBLE,
  CONSTRAINT `fk_flight_airplane1`
    FOREIGN KEY (`idAirplane`)
    REFERENCES `qairline`.`airplane` (`idAirplane`),
  CONSTRAINT `fk_flight_airport1`
    FOREIGN KEY (`idbeginAirport`)
    REFERENCES `qairline`.`airport` (`idairport`),
  CONSTRAINT `fk_flight_airport2`
    FOREIGN KEY (`idendAirport`)
    REFERENCES `qairline`.`airport` (`idairport`),
  CONSTRAINT `fk_flight_admin1`
    FOREIGN KEY (`idAdmin_created`)
    REFERENCES `qairline`.`admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qairline`.`classflight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`classflight` ;

CREATE TABLE IF NOT EXISTS `qairline`.`classflight` (
  `idclassFlight` INT NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(45) NOT NULL,
  `seatAmount` INT UNSIGNED NULL DEFAULT NULL,
  `seatBooked` INT UNSIGNED NULL DEFAULT NULL,
  `currentPrice` INT UNSIGNED NULL DEFAULT NULL,
  `idFlight` INT NOT NULL,
  PRIMARY KEY (`idclassFlight`),
  UNIQUE INDEX `idclassFlight_UNIQUE` (`idclassFlight` ASC) VISIBLE,
  INDEX `fk_classflight_flight1_idx` (`idFlight` ASC) VISIBLE,
  CONSTRAINT `fk_classflight_flight1`
    FOREIGN KEY (`idFlight`)
    REFERENCES `qairline`.`flight` (`idFlight`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qairline`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`customer` ;

CREATE TABLE IF NOT EXISTS `qairline`.`customer` (
  `idCustomer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `numberPhone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idCustomer`),
  UNIQUE INDEX `id_UNIQUE` (`idCustomer` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qairline`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`ticket` ;

CREATE TABLE IF NOT EXISTS `qairline`.`ticket` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `idclassFlight` INT NOT NULL,
  `idCustomer` INT UNSIGNED NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`idTicket`),
  UNIQUE INDEX `idticket_UNIQUE` (`idTicket` ASC) VISIBLE,
  INDEX `fk_ticket_classFlight1_idx` (`idclassFlight` ASC) VISIBLE,
  INDEX `fk_ticket_customer1_idx` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_classFlight1`
    FOREIGN KEY (`idclassFlight`)
    REFERENCES `qairline`.`classflight` (`idclassFlight`),
  CONSTRAINT `fk_ticket_customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `qairline`.`customer` (`idCustomer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qairline`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`notification` ;

CREATE TABLE IF NOT EXISTS `qairline`.`notification` (
  `idNotification` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NULL,
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `unRead` TINYINT(1) NULL DEFAULT 1,
  `idCustomer` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idNotification`),
  UNIQUE INDEX `idNotification_UNIQUE` (`idNotification` ASC) VISIBLE,
  INDEX `fk_notification_customer1_idx` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_notification_customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `qairline`.`customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qairline`.`advertisement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qairline`.`advertisement` ;

CREATE TABLE IF NOT EXISTS `qairline`.`advertisement` (
  `idAdvertisement` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL,
  `type` VARCHAR(45) NULL,
  `image_url` VARCHAR(100) NULL,
  `target_url` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `idAdmin_created` INT NOT NULL,
  PRIMARY KEY (`idAdvertisement`),
  UNIQUE INDEX `idAdvertisement_UNIQUE` (`idAdvertisement` ASC) VISIBLE,
  INDEX `fk_advertisement_admin1_idx` (`idAdmin_created` ASC) VISIBLE,
  CONSTRAINT `fk_advertisement_admin1`
    FOREIGN KEY (`idAdmin_created`)
    REFERENCES `qairline`.`admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- DELIMITER //

-- CREATE TRIGGER gen_ticket_code
-- BEFORE INSERT ON ticket
-- FOR EACH ROW
-- BEGIN
--     DECLARE beginAirportCode VARCHAR(3);
--     DECLARE seatClassCode VARCHAR(3);
--     DECLARE seatOrder INT;

--     -- Lấy mã sân bay khởi hành từ bảng flight
--     SELECT code INTO beginAirportCode
--     FROM airport
--     WHERE idairport = (SELECT idbeginAirport FROM flight WHERE idFlight = (SELECT idFlight FROM classflight WHERE idclassFlight = NEW.idclassFlight));

--     -- Lấy mã hạng vé từ bảng classflight và chuyển đổi thành mã rút gọn
--     SELECT class INTO seatClassCode
--     FROM classflight
--     WHERE idclassFlight = NEW.idclassFlight;

--     -- Chuyển đổi hạng vé sang mã rút gọn: Economy -> Eco, Business -> Bus
--     SET seatClassCode = CASE
--         WHEN seatClassCode = 'Economy' THEN 'ENM'
--         WHEN seatClassCode = 'Business' THEN 'BSN'
--         WHEN seatClassCode = 'First_Class' THEN 'FCS'
--         ELSE 'DEF' -- mặc định cho các hạng khác (nếu có)
--     END;

--     -- Lấy số thứ tự ghế đã đặt và định dạng thành 3 chữ số
--     SELECT seatBooked INTO seatOrder
--     FROM classflight
--     WHERE idclassFlight = NEW.idclassFlight;

--     -- Tạo mã code cho vé
--     SET NEW.code = CONCAT(beginAirportCode, seatClassCode, seatOrder);
-- END//

-- DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE qairline;
SET SQL_SAFE_UPDATES = 0;
-- Dữ liệu cho bảng `airplane`
DELETE FROM airplane;
INSERT INTO airplane () VALUES (), (), (); -- Chỉ cần thêm các dòng trống vì `idAirplane` tự tăng

-- Dữ liệu cho bảng `airport`
DELETE FROM airport;
INSERT INTO airport (name, country, city, code) VALUES 
    ('Tan Son Nhat International Airport', 'Vietnam', 'Ho Chi Minh City', 'SGN'),
    ('Noi Bai International Airport', 'Vietnam', 'Hanoi', 'HAN'),
    ('Da Nang International Airport', 'Vietnam', 'Da Nang', 'DAD'),
    ('Cam Ranh International Airport', 'Vietnam', 'Nha Trang', 'CXR'),
    ('Changi Airport', 'Singapore', 'Singapore', 'SIN'),
    ('Incheon International Airport', 'South Korea', 'Incheon', 'ICN');

-- Dữ liệu cho bảng `admin`
DELETE FROM admin;
INSERT INTO admin (email, password, username) VALUES 
    ('admin@gmail.com', 'admin', 'admin1'),
    ('admin2@qairline.com', 'admin2', 'admin2');

-- Dữ liệu cho bảng `flight`
DELETE FROM flight;
INSERT INTO flight (timeStart, timeEnd, idbeginAirport, idendAirport, idAirplane, idAdmin_created) VALUES 
    ('2023-12-01 08:00:00', '2023-12-01 10:00:00', 1, 2, 1, 1),
    ('2023-12-05 09:00:00', '2023-12-05 12:30:00', 2, 5, 2, 1),
    ('2023-12-10 14:00:00', '2023-12-10 18:00:00', 3, 4, 1, 2),
    ('2023-12-15 17:00:00', '2023-12-15 21:30:00', 6, 1, 1, 1);

-- Dữ liệu cho bảng `classflight`
DELETE FROM classflight;
INSERT INTO classflight (class, seatAmount, seatBooked, currentPrice, idFlight) VALUES 
    ('Economy', 150, 50, 4000000, 1),
    ('Business', 20, 5, 8000000, 1),
    ('Economy', 150, 60, 5500000, 2),
    ('Business', 20, 8, 12000000, 2),
    ('Economy', 180, 70, 5000000, 3),
    ('Business', 25, 10, 9000000, 3),
    ('Economy', 160, 80, 6000000, 4),
    ('Business', 20, 9, 14000000, 4),
    ('First-Class', 10, 2, 15000000, 1),
    ('First-Class', 10, 1, 18000000, 2),
    ('First-Class', 12, 3, 17000000, 3),
    ('First-Class', 10, 4, 20000000, 4);

-- Dữ liệu cho bảng `customer`
DELETE FROM customer;
INSERT INTO customer (username, email, password, numberPhone) VALUES 
    ('nguyenphuc', 'phuc.nguyen@qairline.com', 'password123', '0901234567'),
    ('lethithanh', 'thanh.le@qairline.com', 'password456', '0902345678'),
    ('phamvanminh', 'minh.pham@qairline.com', 'password789', '0903456789'),
    ('tranthihuyen', 'huyen.tran@qairline.com', 'password101', '0904567890');

-- Dữ liệu cho bảng `ticket`
DELETE FROM ticket;
INSERT INTO ticket (idclassFlight, idCustomer, price, status) VALUES 
    (1, 1, 4000000, 'Paid'),
    (2, 1, 8000000, 'Paid'),
    (3, 2, 5500000, 'Paid'),
    (4, 3, 12000000, 'Unpaid'),
    (5, 1, 5000000, 'Paid'),
    (6, 2, 9000000, 'Unpaid'),
    (7, 3, 6000000, 'Paid'),
    (8, 4, 14000000, 'Unpaid');

-- Dữ liệu cho bảng `notification`
DELETE FROM notification;
INSERT INTO notification (content, unRead, idCustomer) VALUES 
    ('Your flight from Ho Chi Minh City to Hanoi has been successfully booked.', 1, 1),
    ('Your payment for the Hanoi to Singapore flight is successful.', 1, 2),
    ('Booking not confirmed. Please try again.', 1, 3),
    ('Your ticket has been updated. Please check your booking details.', 0, 4);

-- Dữ liệu cho bảng `advertisement`
-- INSERT INTO advertisement (description, type, image_url, target_url, created_at, idAdmin_created) VALUES 
--     ('20% off all international flights in December!', 'banner', 'https://example.com/image1.jpg', 'https://qairline.com/promotion', NOW(), 1),
--     ('Special deals on flights to Singapore!', 'popup', 'https://example.com/image2.jpg', 'https://qairline.com/singapore-sale', NOW(), 2);
