name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh &&
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa &&
        chmod 600 ~/.ssh/id_rsa &&
        ssh-keyscan -H ${{ secrets.HOST_NAME }} >> ~/.ssh/known_hosts

    - name: Deploy Frontend
      run: |
        ssh ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} "cd QAirline/src/FE && git pull && npm install && npm run build && pm2 restart frontend"

    - name: Deploy Backend
      run: |
        ssh ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} "cd QAirline/src/server && git pull && npm install && pm2 restart backend"
